# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'AeroGuardMobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Google Mobile Ads SDK
  pod 'Google-Mobile-Ads-SDK'
  # Firebase Push Notifications
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'

end

target 'AeroGuardWidgetExtension' do
  use_frameworks!
  # Widget doesn't need ads
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
