require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '16.0'
prepare_react_native_project!

target 'AeroGuardMobile' do
  # config = use_native_modules!
  config = { :reactNativePath => "../node_modules/react-native" }

  pod 'react-native-geolocation-service', :path => '../node_modules/react-native-geolocation-service'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)
  end
end
